# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_rcpp <- function(N, nsamp) {
    .Call('perccal_sample_rcpp', PACKAGE = 'perccal', N, nsamp)
}

Cquantile <- function(xx, p) {
    .Call('perccal_Cquantile', PACKAGE = 'perccal', xx, p)
}

Cdboot_multi <- function(xxyy, lgridlo, lgridhi, B, B2, G) {
    .Call('perccal_Cdboot_multi', PACKAGE = 'perccal', xxyy, lgridlo, lgridhi, B, B2, G)
}

